/*
 * 说明：
 * 1. 使用管道符定义单复数，格式为 `单数 | 复数`。
 */

import { LocaleIdentifiers } from "./types";

const English: LocaleIdentifiers = {
	colon: ": ",
	semicolon: "; ",
	caesura: ", ",
	welcome: "Chào Mừng",
	home: "Trang nhà",
	category: {
		_: "Danh mục",
		anime: "Anime",
		music: "Âm nhạc",
		otomad: "Âm-MAD",
		tech: "Công nghệ",
		design: "Thiết kế",
		game: "Trò chơi",
		other: "Khác",
	},
	content: "Nội dung",
	search: "Tìm kiếm",
	button: "Nút",
	button_disabled: "Nút bị vô hiệu",
	button_clicked: "Nút này đã được bấm vào kkkkk",
	confetti: "Pháo bông",
	send: "Gửi",
	query: "Hàng đợi",
	show_alert: "Hiện thông báo",
	toggle_switch: "Toggle Switch",
	on: "Bật",
	off: "Tắt",
	disabled: "Đã tắt",
	background: "Hình nền",
	animated_background: "Hình nền động",
	custom_background: "Hình nền",
	light: "Bật đèn",
	dark: "Tắt đèn",
	system: "Chiếu theo bộ màu giao diện hệ thống",
	pink: "Hồng xinh xắn",
	sky: "Thiên Thanh",
	blue: "Chino",
	green: "Chiya",
	orange: "Kokoa",
	purple: "Rize",
	custom: "Tùy chỉnh",
	checkbox: "Hộp đanh dấu",
	search_settings: "Cài đặt tìm kiếm",
	appearance: "Giao diện",
	scheme: "Chủ đề",
	palette: "Bộ màu",
	language: "Ngôn ngữ",
	tag: "Thẻ",
	all: "Tất cả",
	video: "Videos",
	image: "Hình ảnh",
	logo_hidden: "Logo bị ẩn",
	logo_half: "Logo hiện bán phần",
	logo_show: "Logo hiện toàn phần",
	comments: "Bình luận",
	uploaders_lovin_it: "Uploader's lovin' it",
	finish: "Đăng tải video thành công.",
	you_know_too_much: "Hơi bị lộ liễu rồi đấy.",
	dashboard: "Thứ hạng",
	account: "Tài khoản",
	profile: "Hồ sơ",
	traces: "Traces",
	privacy: "Riêng tư",
	security: "Bảo mật",
	login_options: "Tùy chọn đăng nhập",
	password: {
		_: "Mật khẩu",
		forgot: "Tôi quên mật khẩu",
		retype: "Nhập lại mật khẩu",
		change: "Đổi mật khẩu",
		current: "Mật khẩu hiện hành",
		new: "Mật khẩu mới",
		new_retype: "Nhập lại mật khẩu mới",
		hint: "Gợi ý mật khẩu",
	},
	account_linking: "Liên kết tài khoản",
	blocklist: {
		_: "Sổ đen",
		ban: {
			_: "Cấm",
			description: "Các người dùng mà bạn không muốn liên hệ.",
		},
		hide: {
			_: "Ẩn",
			description: "Các người dùng bạn không muốn nhìn thấy (trừ phi bạn truy cập trang cá nhân của họ).",
		},
		tags: {
			description: "Dùng chế độ lọc thẻ, loại ra các nội dung bạn không muốn thấy.",
		},
		keywords: {
			description: "Dùng chế độ lọc từ khóa, loại ra các nội dung bạn không muốn thấy.",
		},
		regexp: {
			description: "Dùng phương thức lập trình biểu thức toán học, loại ra các nội dung bạn không muốn thấy.",
		},
	},
	player: {
		_: "Người chơi",
		speed: {
			resample_audio: "Phối lại âm thanh",
			continuous: "Điều khiển liên tục",
		},
	},
	danmaku: {
		_: "Đạn mạc",
		send: "Gửi bình luận",
		history: "Lịch sử bình luận",
		format: {
			mode: {
				rtl: "Cuộn",
				top: "Trên",
				bottom: "Dưới",
				ltr: "Đảo chiều",
			},
			send_as_creator: "Phóng Đạn mạc với tư cách người đăng tải", // NEW
		},
		list: {
			loading: "Đang tải Đạn mạc",
			thead: {
				time: "Thời gian",
				content: "Nội dung",
				sending_time: "Thời gian phóng đi",
			},
		},
	},
	preference: "Tùy chỉnh",
	accessibility: "Giao diện",
	about: "Thông tin về chúng tôi",
	experimental: "Chế độ thử nghiệm",
	user_settings: "Thiết đặt người dùng",
	app_settings: "Thiết đặt ứng dụng",
	male: "Nam",
	female: "Nữ",
	birthday: "Sinh nhật",
	email: "Email",
	email_address: "Email",
	authenticator: "Chứng thực",
	current_email: "Current Email",
	modification_date: "Ngày chỉnh sửa",
	addition_date: "Ngày thêm",
	modify: "Sửa",
	save: "Lưu",
	add: "Thêm",
	apply: "Áp dụng",
	reset: "Hoàn nguyên",
	history: "Lịch sử",
	favorite: "Thích",
	favorites: "Mục ưa thích",
	favorite_verb: "Thêm vào Mục ưa thích",
	feed: "Tường",
	upload: "Đăng tải",
	messages: "Tin nhắn",
	login: "Đăng nhập",
	logout: "Đăng xuất",
	register: "Đăng ký",
	verification_code: "Mã xác nhận",
	close: "Đóng",
	current_page_label: "Trang {0} trên tổng số {1} trang",
	switch_page_label: "Dời sang trang {0}",
	selected_item_label: "Lựa chọn mục: ",
	happy: "Vui",
	greet: "Chào",
	awa: "Moe",
	sad: "Buồn",
	embarrassed: "Ngại ngùng",
	upvote: "Tán thành",
	downvote: "Không tán thành",
	share: "Chia sẻ",
	play: "Phát",
	pause: "Tạm dừng",
	rating: "Xếp hạng",
	bold: "Đậm",
	italic: "Nghiêng",
	underline: "Gạch dưới",
	strikethrough: "Gạch ngang",
	at_person: "At",
	kaomoji: "Biểu cảm",
	associate_existing: "Video liên quan",
	reply: "Phản hồi",
	more: "Xem thêm",
	delete: "Xóa",
	copy: "Sao chép",
	pin: "Ghim",
	unpin: "Tháo ghim",
	report: "Báo cáo",
	original: "Nguyên tác",
	repost: "Đăng lại",
	authorized_repost: "Đăng lại dưới sự chấp thuận của tác giả",
	ensure_original: "Tôi khẳng định nội dung này là nguyên tác",
	original_author: "Tác giả nguyên tác",
	original_link: "Liên kết đến nguyên tác",
	title: "Tựa",
	tags: "Các thẻ",
	press_enter_to_add: "Nhập Enter để thêm",
	description_of_creation: "Mô tả",
	push_to_feed: "Đưa lên tường",
	cover: "Bìa",
	select_cover: "Chọn bìa",
	series: "Loạt",
	audio: "Âm thanh",
	photo: "Ảnh",
	album: "Album",
	follow: "Theo dõi",
	following: "Đang theo dõi",
	fans: "Người hâm mộ",
	views_video: "Lượt xem",
	join_time: "Đã tham gia",
	user_info: "Thông tin người dùng",
	acknowledgement: "Các tuyên bố",
	friendly_links: "Liên kết ngoài",
	latest: "Mới nhất",
	test: "Thử nghiệm",
	error_pages: "Trang báo lỗi",
	upload_date: "Ngày đăng",
	sort: {
		by: "Sắp xếp",
		view: "Theo lượt xem",
		danmaku: "Theo số Đạn mạc",
		comment: "Theo số bình luận",
		favorite: "Theo số lượt thích",
	},
	view: {
		_: "Lượt xem",
		list: "Danh sách",
		grid: "Dạng lưới",
		tile: "Tựa",
	},
	duration: "Thời lượng",
	viewers: "Người xem",
	are_watching: "đang xem",
	step: {
		next: "Kế tiếp",
		previous: "Trước đó",
		ok: "OK",
		cancel: "Hủy bỏ",
	},
	loginwindow: {
		login_welcome: "Chào mừng",
		login_to_forgot: "Quên mật khẩu",
		login_to_register: "Đăng ký tài khoản",
		register_to_login: "Tiếp tục đăng nhập",
		forgot_to_login: "Tôi đã tìm thấy mật khẩu",
		register_email_sent_info: "Chúng tôi đã gửi một mã xác thực vào địa chỉ email của bạn.\nHãy bấm gửi lại mã trong trường hợp không nhận được mã.",
		forgot_info: "Hãy nhập địa chỉ email.\nChúng tôi sẽ gửi mã xác thực vào địa chỉ email.",
		reset_successful_info: "Chứng thực thành công!\nHãy nhập mật khẩu, và ghi nhớ mật khẩu đó.",
	},
	settings_unselected: "Vui lòng nhập Tab",
	combobox_unselected: "Vui lòng chọn",
	settings: {
		_: "Settings",
		profile: {
			edit_banner: "Chỉnh sửa phông nền",
			edit_avatar: "Chỉnh sửa ảnh đại diện",
		},
		privacy: {
			allow_cookies: "Cho phép dùng các Cookie",
			info_visibility: "Hiển thị thông tin",
		},
		appearance: {
			other: {
				sharp_mode: "Chế độ sắc nét",
				flat_mode: "Chế độ đơn giản",
				colorful_navbar: "Thêm hiệu ứng màu sắc vào thanh tìm kiếm",
			},
		},
		about: {
			repositories: "Mã nguồn",
			creative_team: "Đội ngũ sáng tạo",
			staff: {
				webmistress: "Chủ trì",
				designer: "Thiết kế",
				frontend: "Thiết kế giao diện",
				backend: "Thiết kế nguồn",
				translator: "Dịch giả",
			},
			technologies_used: "Có sự sử dụng của",
		},
	},
	user: {
		name: "Tên người dùng",
		name_requirements: 'Từ 1 đến 20 ký tự, chỉ bao gồm chữ số và các mẫu tự Latinh, Hán tự, tiếng Hàn, Hiragana và Katakana, và ký tự đặc biệt "-", "_"',
		bio: "Lý lịch",
		gender: "Giới tính",
		memo: "Phụ chú",
		age: "Tuổi",
	},
	zhs: "tiếng Trung - giản thể",
	zht: "tiếng Trung - phồn thể",
	en: "tiếng Anh",
	ja: "tiếng Nhật",
	ko: "tiếng Hàn",
	vi: "Tiếng Việt",
	development_test_page: "Trang thử nghiệm dành cho nhà phát triển",
	components_test_page: "Trang thử nghiệm từng phần",
	view_cover: "Xem bìa",
	watch_later: "Xem sau",
	download_video: "Tải video",
	report_creation: "Báo cáo",
	forgot_password: "Quên mật khẩu",
	reset_password: "Đặt lại mật khẩu",
	format: "Định dạng",
	text: {
		_: "Văn bản",
		size: "Cỡ chữ",
	},
	color: "Màu",
	mode: "Chế độ",
	size: {
		_: "Cỡ chữ",
		mini: "Cực tiểu",
		small: "Nhỏ",
		medium: "Nhỡ",
		large: "Lớn",
		extra_large: "Cực đại",
	},
	unknown: "Không xác định",
	shortcut_key: "Phím tắt",
	guide: "Hướng dẫn",
	regexp: "Biểu thức căn bản",
	keywords: "Từ khóa",
	user_page: {
		_: "Trang người dùng",
		title_suffix: "'s User Page",
	},
	manage_content: "Quản lý nội dung",
	add_to_blocklist: "Thêm vào sổ đen",
	platform: {
		bilibili: "Bilibili",
		niconico: "Niconico",
		otomad_wiki: "Otomad Wiki",
		weibo: "Weibo",
		twitter: "Twitter",
		qq: "QQ",
		youtube: "YouTube",
		discord: "Discord",
		telegram: "Telegram",
		midishow: "MidiShow",
	},
	modify_memo: "Sửa phụ chú",
	add_to_group: "Thêm vào nhóm",
	navigation: {
		_: "Tìm kiếm",
		back: "Quay lại",
	},
	other: "Khác",
	color_picker: "Chọn màu",
};

export default English;
