import { PREFERENTIAL_ROUTE } from "../shared/constants";

export const THEME_COOKIE_BANDER_SCRIPT_TEMPLATE_NAME = "theme-cookie-binding.js";
export const THEME_COOKIE_BANDER_SCRIPT_ROUTE = PREFERENTIAL_ROUTE + THEME_COOKIE_BANDER_SCRIPT_TEMPLATE_NAME;
