// DO NOT EDIT THIS FILE DIRECTLY! Go to the Crowdin project website to translate it: https://crowdin.com/project/kirakira

import type { LocaleIdentifiers } from "./types";

export default {
	category: {},
	scheme: {},
	palette: {},
	language: {
		_: "언어",
		zhs: "중국어 간체",
		zht: "중국어 번체",
		en: "영어",
		ja: "일본어",
		ko: "한국인",
		vi: "베트남어",
		id: "인도네시아어",
	},
	background: {},
	appearance: {},
	tag: {},
	settings: {},
	profile: {},
	privacy: {},
	password: {},
	blocklist: {
		ban: {},
		hide: {},
		tag: {},
		keyword: {},
		regexp: {},
	},
	player: {
		speed: {},
		quality: {},
		error: {},
	},
	danmaku: {
		format: {
			mode: {},
		},
		list: {
			thead: {},
		},
	},
	shortcut_key: {},
	about: {
		repositories: {},
		staff: {},
	},
	favorites: {},
	upload: {},
	kaomoji: {},
	sort: {},
	view: {},
	step: {},
	loginwindow: {},
	unselected: {},
	user: {},
	format: {},
	text: {},
	size: {},
	user_page: {},
	platform: {},
	navigation: {},
	toast: {},
	confirm: {},
} as const satisfies LocaleIdentifiers;
