/**
 * Kirakira Backend API
 * The API for Kirakira
 *
 * OpenAPI spec version: 0.0.1
 * Contact: horahora1567@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class VideoDetail200ResponseVideoRecommendations {
    'title'?: string;
    'thumbnailLoc'?: string;
    'videoID'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "Title",
            "type": "string",
            "format": ""
        },
        {
            "name": "thumbnailLoc",
            "baseName": "ThumbnailLoc",
            "type": "string",
            "format": ""
        },
        {
            "name": "videoID",
            "baseName": "VideoID",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VideoDetail200ResponseVideoRecommendations.attributeTypeMap;
    }

    public constructor() {
    }
}

