declare const eases: {
	linear: string;
	ease: string;
	easeIn: string;
	easeOut: string;
	easeInOut: string;
	easeInQuad: string;
	easeInCubic: string;
	easeInQuart: string;
	easeInQuint: string;
	easeInSine: string;
	easeInExpo: string;
	easeInCirc: string;
	easeInBack: string;
	easeOutQuad: string;
	easeOutCubic: string;
	easeOutQuart: string;
	easeOutQuint: string;
	easeOutSine: string;
	easeOutExpo: string;
	easeOutCirc: string;
	easeOutBack: string;
	easeInOutQuad: string;
	easeInOutCubic: string;
	easeInOutQuart: string;
	easeInOutQuint: string;
	easeInOutSine: string;
	easeInOutExpo: string;
	easeInOutCirc: string;
	easeInOutBack: string;
	easeInMax: string;
	easeOutMax: string;
	easeInOutMax: easeInOutMax;
};
export default eases;
