/**
 * Kirakira Backend API
 * The API for Kirakira
 *
 * OpenAPI spec version: 0.0.1
 * Contact: horahora1567@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Videos200ResponsePaginationData {
    'pathsAndQueryStrings'?: Array<string>;
    'pages'?: Array<number>;
    'currentPage'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pathsAndQueryStrings",
            "baseName": "PathsAndQueryStrings",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "pages",
            "baseName": "Pages",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "currentPage",
            "baseName": "CurrentPage",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Videos200ResponsePaginationData.attributeTypeMap;
    }

    public constructor() {
    }
}

