/**
 * Kirakira Backend API
 * The API for Kirakira
 *
 * OpenAPI spec version: 0.0.1
 * Contact: horahora1567@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VideoDetail200ResponseDetails } from '../models/VideoDetail200ResponseDetails';
import { HttpFile } from '../http/http';

export class VideoDetail200Response {
    'details'?: VideoDetail200ResponseDetails;
    'tags'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "details",
            "baseName": "Details",
            "type": "VideoDetail200ResponseDetails",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "Tags",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VideoDetail200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

