name: Sync Develop to Locale Branch
on:
  push:
    branches:
      - develop
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Merge develop -> locale
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

          git checkout develop
          git fetch origin
          git checkout locale-2023091301-Backup-Ranne
          git pull
          git merge origin/develop --no-commit --no-ff
          git push origin locale-2023091301-Backup-Ranne
