name: Sync Develop to Production Branch
on:
  push:
    branches:
      - develop
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Merge develop -> production
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git config pull.rebase false

          git checkout production
          git pull origin develop
          git push origin production
